[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.71it/s]1it [00:13, 13.75s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.12s/it]
0it [00:00, ?it/s]1it [00:05,  5.18s/it]
0it [00:00, ?it/s]1it [00:04,  4.39s/it]
START
2020-10-23
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
START
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 48, in main
    upload_bigQuerry()
  File "run.py", line 20, in upload_bigQuerry
    df = io.get_orcamento_executado()
  File "../scripts/io.py", line 90, in get_orcamento_executado
    firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()
  File "/home/m/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/home/m/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/m/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/m/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]

[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.38it/s]1it [00:14, 14.72s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.25s/it]
0it [00:00, ?it/s]1it [00:04,  4.40s/it]
0it [00:00, ?it/s]1it [00:05,  5.23s/it]
START
2020-10-25
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.50it/s]1it [00:13, 13.36s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
0it [00:00, ?it/s]1it [00:04,  4.56s/it]
0it [00:00, ?it/s]1it [00:04,  4.16s/it]
START
2020-10-26
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.41it/s]1it [00:13, 13.20s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.48s/it]
0it [00:00, ?it/s]1it [00:04,  4.55s/it]
0it [00:00, ?it/s]1it [00:05,  5.62s/it]
START
2020-10-27
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.20it/s]1it [00:22, 22.14s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.01s/it]
0it [00:00, ?it/s]1it [00:04,  4.17s/it]
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
START
2020-10-28
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.32it/s]1it [00:15, 15.57s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.42s/it]
0it [00:00, ?it/s]1it [00:03,  3.99s/it]
0it [00:00, ?it/s]1it [00:06,  6.55s/it]
START
2020-10-29
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.52it/s]1it [00:14, 14.90s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.68s/it]
0it [00:00, ?it/s]1it [00:06,  6.67s/it]
0it [00:00, ?it/s]1it [00:04,  4.16s/it]
START
2020-10-30
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.52it/s]1it [00:11, 11.61s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.68s/it]
0it [00:00, ?it/s]1it [00:06,  6.03s/it]
0it [00:00, ?it/s]1it [00:03,  3.98s/it]
START
2020-10-31
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.55it/s]1it [00:14, 14.63s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:06,  6.34s/it]
0it [00:00, ?it/s]1it [00:05,  5.51s/it]
0it [00:00, ?it/s]1it [00:04,  4.61s/it]
START
2020-11-01
DONE!
[WDM] - Getting latest mozilla release info for v0.27.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0]
0it [00:00, ?it/s]1it [00:00,  2.55it/s]1it [00:15, 15.96s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.27.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.53s/it]
0it [00:00, ?it/s]1it [00:06,  6.15s/it]
0it [00:00, ?it/s]1it [00:04,  4.58s/it]
START
2020-11-02
DONE!
[WDM] - There is no [linux64] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.49it/s]1it [00:12, 12.88s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.21s/it]
0it [00:00, ?it/s]1it [00:04,  4.54s/it]
0it [00:00, ?it/s]1it [00:06,  6.58s/it]
START
2020-11-03
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.04it/s]1it [00:13, 13.83s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:03,  3.59s/it]
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
0it [00:00, ?it/s]1it [00:03,  3.88s/it]
START
2020-11-04
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.41it/s]1it [00:13, 13.03s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
0it [00:00, ?it/s]1it [00:06,  6.65s/it]
0it [00:00, ?it/s]1it [00:07,  7.01s/it]
START
2020-11-05
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.41it/s]1it [00:15, 15.60s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.62s/it]
0it [00:00, ?it/s]1it [00:04,  4.04s/it]
0it [00:00, ?it/s]1it [00:04,  4.83s/it]
START
2020-11-06
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.71it/s]1it [00:12, 12.40s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.26s/it]
0it [00:00, ?it/s]1it [00:03,  3.82s/it]
0it [00:00, ?it/s]1it [00:03,  3.96s/it]
START
2020-11-07
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.53it/s]1it [00:10, 10.73s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:07,  7.05s/it]
0it [00:00, ?it/s]1it [00:03,  3.91s/it]
0it [00:00, ?it/s]1it [00:06,  6.57s/it]
START
2020-11-08
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.54it/s]1it [00:13, 13.67s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.16s/it]
0it [00:00, ?it/s]1it [00:05,  5.80s/it]
0it [00:00, ?it/s]1it [00:03,  3.90s/it]
START
2020-11-09
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.66it/s]1it [00:12, 12.41s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.55s/it]
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
0it [00:00, ?it/s]1it [00:05,  5.41s/it]
START
2020-11-10
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.44it/s]1it [00:13, 13.15s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:06,  6.44s/it]
0it [00:00, ?it/s]1it [00:06,  6.28s/it]
0it [00:00, ?it/s]1it [00:08,  8.07s/it]
START
2020-11-11
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.53it/s]1it [00:15, 15.85s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:07,  7.17s/it]
0it [00:00, ?it/s]1it [00:06,  6.67s/it]
0it [00:00, ?it/s]1it [00:03,  3.96s/it]
START
2020-11-12
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.46it/s]1it [00:14, 14.99s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.45s/it]
0it [00:00, ?it/s]1it [00:04,  4.47s/it]
0it [00:00, ?it/s]1it [00:07,  7.31s/it]
START
2020-11-13
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.54it/s]1it [00:11, 11.83s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.31s/it]
0it [00:00, ?it/s]1it [00:04,  4.98s/it]
0it [00:00, ?it/s]1it [00:03,  3.73s/it]
START
2020-11-14
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.47it/s]1it [00:13, 13.53s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.83s/it]
0it [00:00, ?it/s]1it [00:04,  4.21s/it]
0it [00:00, ?it/s]1it [00:05,  5.64s/it]
START
2020-11-15
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.69it/s]1it [00:17, 17.89s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.30s/it]
0it [00:00, ?it/s]1it [00:03,  3.71s/it]
0it [00:00, ?it/s]1it [00:04,  4.03s/it]
START
2020-11-16
DONE!
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.34it/s]1it [00:21, 21.41s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.85s/it]
0it [00:00, ?it/s]1it [00:04,  4.37s/it]
0it [00:00, ?it/s]1it [00:08,  8.08s/it]
START
2020-11-17
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.55it/s]1it [00:15, 15.20s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.32s/it]
0it [00:00, ?it/s]1it [00:08,  8.89s/it]
0it [00:00, ?it/s]1it [00:05,  5.10s/it]
2020-11-18
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.39it/s]1it [00:16, 16.83s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.98s/it]
0it [00:00, ?it/s]1it [00:04,  4.61s/it]
0it [00:00, ?it/s]1it [00:04,  4.52s/it]
2020-11-19
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.46it/s]1it [00:18, 18.87s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.31s/it]
0it [00:00, ?it/s]1it [00:04,  4.76s/it]
0it [00:00, ?it/s]1it [00:04,  4.73s/it]
2020-11-20
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.53it/s]1it [00:19, 19.70s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.44s/it]
0it [00:00, ?it/s]1it [00:04,  4.38s/it]
0it [00:00, ?it/s]1it [00:04,  4.84s/it]
2020-11-21
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.44it/s]1it [00:20, 20.41s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.71s/it]
0it [00:00, ?it/s]1it [00:04,  4.72s/it]
0it [00:00, ?it/s]1it [00:04,  4.80s/it]
2020-11-22
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.40it/s]1it [00:17, 17.19s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:06,  6.43s/it]
0it [00:00, ?it/s]1it [00:05,  5.50s/it]
0it [00:00, ?it/s]1it [00:06,  6.16s/it]
2020-11-23
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.45it/s]1it [00:18, 18.27s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.03s/it]
0it [00:00, ?it/s]1it [00:04,  4.32s/it]
0it [00:00, ?it/s]1it [00:05,  5.36s/it]
2020-11-24
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.56it/s]1it [00:19, 19.11s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.56s/it]
0it [00:00, ?it/s]1it [00:04,  4.83s/it]
0it [00:00, ?it/s]1it [00:04,  4.64s/it]
2020-11-25
DONE!
START

-------------------------------------------------------------------------------
connection.py 159 _new_conn
conn = connection.create_connection(

connection.py 61 create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

socket.py 918 getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror:
-3
Temporary failure in name resolution

-------------------------------------------------------------------------------
connectionpool.py 670 urlopen
httplib_response = self._make_request(

connectionpool.py 381 _make_request
self._validate_conn(conn)

connectionpool.py 976 _validate_conn
conn.connect()

connection.py 308 connect
conn = self._new_conn()

connection.py 171 _new_conn
raise NewConnectionError(

urllib3.exceptions.NewConnectionError:
<urllib3.connection.HTTPSConnection object at 0x7efdaceb2880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

-------------------------------------------------------------------------------
adapters.py 439 send
resp = conn.urlopen(

connectionpool.py 724 urlopen
retries = retries.increment(

retry.py 439 increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efdaceb2880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 50 get_orcamento_executado
firefox = webdriver.Firefox(options=options,firefox_profile=profile, executable_path = GeckoDriverManager().install())

firefox.py 28 install
return self._get_driver_path(self.driver)

manager.py 22 _get_driver_path
driver_version = driver.get_version()

driver.py 40 get_version
return self.get_latest_release_version()

driver.py 87 get_latest_release_version
resp = requests.get(url=self.latest_release_url,

api.py 76 get
return request('get', url, params=params, **kwargs)

api.py 61 request
return session.request(method=method, url=url, **kwargs)

sessions.py 530 request
resp = self.send(prep, **send_kwargs)

sessions.py 643 send
r = adapter.send(request, **kwargs)

adapters.py 516 send
raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efdaceb2880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
START

-------------------------------------------------------------------------------
connection.py 159 _new_conn
conn = connection.create_connection(

connection.py 61 create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

socket.py 918 getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror:
-3
Temporary failure in name resolution

-------------------------------------------------------------------------------
connectionpool.py 670 urlopen
httplib_response = self._make_request(

connectionpool.py 381 _make_request
self._validate_conn(conn)

connectionpool.py 976 _validate_conn
conn.connect()

connection.py 308 connect
conn = self._new_conn()

connection.py 171 _new_conn
raise NewConnectionError(

urllib3.exceptions.NewConnectionError:
<urllib3.connection.HTTPSConnection object at 0x7f2bca9a3580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

-------------------------------------------------------------------------------
adapters.py 439 send
resp = conn.urlopen(

connectionpool.py 724 urlopen
retries = retries.increment(

retry.py 439 increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2bca9a3580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 50 get_orcamento_executado
firefox = webdriver.Firefox(options=options,firefox_profile=profile, executable_path = GeckoDriverManager().install())

firefox.py 28 install
return self._get_driver_path(self.driver)

manager.py 22 _get_driver_path
driver_version = driver.get_version()

driver.py 40 get_version
return self.get_latest_release_version()

driver.py 87 get_latest_release_version
resp = requests.get(url=self.latest_release_url,

api.py 76 get
return request('get', url, params=params, **kwargs)

api.py 61 request
return session.request(method=method, url=url, **kwargs)

sessions.py 530 request
resp = self.send(prep, **send_kwargs)

sessions.py 643 send
r = adapter.send(request, **kwargs)

adapters.py 516 send
raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2bca9a3580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.46it/s]1it [00:12, 12.56s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.23s/it]
0it [00:00, ?it/s]1it [00:05,  5.56s/it]
0it [00:00, ?it/s]1it [00:05,  5.24s/it]
2020-11-30
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.47it/s]1it [00:14, 14.74s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:05,  5.08s/it]
0it [00:00, ?it/s]1it [00:05,  5.27s/it]
0it [00:00, ?it/s]1it [00:05,  5.73s/it]
2020-12-01
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.48it/s]1it [00:12, 12.82s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:06,  6.95s/it]
0it [00:00, ?it/s]1it [00:05,  5.44s/it]
0it [00:00, ?it/s]1it [00:04,  4.58s/it]
2020-12-03
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.44it/s]1it [00:15, 15.41s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.20s/it]
0it [00:00, ?it/s]1it [00:04,  4.10s/it]
0it [00:00, ?it/s]1it [00:05,  5.80s/it]
2020-12-04
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.41it/s]1it [00:12, 12.85s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.28s/it]
0it [00:00, ?it/s]1it [00:04,  4.51s/it]
0it [00:00, ?it/s]1it [00:08,  8.21s/it]
2020-12-05
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.49it/s]1it [00:11, 11.45s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.75s/it]
0it [00:00, ?it/s]1it [00:05,  5.67s/it]
0it [00:00, ?it/s]1it [00:07,  7.58s/it]
2020-12-06
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.40it/s]1it [00:13, 13.65s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.57s/it]
0it [00:00, ?it/s]1it [00:04,  4.06s/it]
0it [00:00, ?it/s]1it [00:07,  7.08s/it]
2020-12-07
DONE!
START

-------------------------------------------------------------------------------
connection.py 158 _new_conn
conn = connection.create_connection(

connection.py 57 create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

socket.py 918 getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror:
-3
Temporary failure in name resolution

-------------------------------------------------------------------------------
connectionpool.py 597 urlopen
httplib_response = self._make_request(conn, method, url,

connectionpool.py 343 _make_request
self._validate_conn(conn)

connectionpool.py 839 _validate_conn
conn.connect()

connection.py 301 connect
conn = self._new_conn()

connection.py 167 _new_conn
raise NewConnectionError(

urllib3.exceptions.NewConnectionError:
<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb181731f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

-------------------------------------------------------------------------------
adapters.py 439 send
resp = conn.urlopen(

connectionpool.py 637 urlopen
retries = retries.increment(method, url, error=e, _pool=self,

retry.py 399 increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb181731f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 50 get_orcamento_executado
firefox = webdriver.Firefox(options=options,firefox_profile=profile, executable_path = GeckoDriverManager().install())

firefox.py 28 install
return self._get_driver_path(self.driver)

manager.py 22 _get_driver_path
driver_version = driver.get_version()

driver.py 40 get_version
return self.get_latest_release_version()

driver.py 87 get_latest_release_version
resp = requests.get(url=self.latest_release_url,

api.py 76 get
return request('get', url, params=params, **kwargs)

api.py 61 request
return session.request(method=method, url=url, **kwargs)

sessions.py 530 request
resp = self.send(prep, **send_kwargs)

sessions.py 643 send
r = adapter.send(request, **kwargs)

adapters.py 516 send
raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError:
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb181731f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.60it/s]1it [00:51, 51.61s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 29 upload_bigQuerry
previsto = io.get_orcamento_receita('previsto')

io.py 208 get_orcamento_receita
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.59it/s]1it [00:22, 22.75s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 32 upload_bigQuerry
io.to_gbq(previsto,'receita_previsto_2020','orcamento','gabinete-sv', if_exists='replace')

io.py 283 to_gbq
credentials = _get_credentials_gbq(),

io.py 257 _get_credentials_gbq
credentials = pydata_google_auth.get_user_credentials(

auth.py 245 get_user_credentials
credentials = credentials_cache.load()

cache.py 190 load
return _load_user_credentials_from_file(self._path)

cache.py 88 _load_user_credentials_from_file
return _load_user_credentials_from_info(credentials_json)

cache.py 53 _load_user_credentials_from_info
credentials.refresh(request)

credentials.py 200 refresh
access_token, refresh_token, expiry, grant_response = _client.refresh_grant(

_client.py 248 refresh_grant
response_data = _token_endpoint_request(request, token_uri, body)

_client.py 105 _token_endpoint_request
response = request(method="POST", url=token_uri, headers=headers, body=body)

requests.py 188 __call__
six.raise_from(new_exc, caught_exc)

<string> 3 raise_from


google.auth.exceptions.TransportError:
HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6a93c8dfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]
0it [00:00, ?it/s]1it [00:00,  2.14it/s]1it [00:38, 38.06s/it]
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
0it [00:00, ?it/s]1it [00:04,  4.86s/it]
0it [00:00, ?it/s]1it [00:04,  4.34s/it]
0it [00:00, ?it/s]1it [00:05,  5.94s/it]
2020-12-14
DONE!
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 98 get_orcamento_executado
df = pd.read_csv(path+'/{}_orcamento_{}.csv'.format(today, year), encoding='windows-1254')

parsers.py 686 read_csv
return _read(filepath_or_buffer, kwds)

parsers.py 452 _read
parser = TextFileReader(fp_or_buf, **kwds)

parsers.py 946 __init__
self._make_engine(self.engine)

parsers.py 1178 _make_engine
self._engine = CParserWrapper(self.f, **self.options)

parsers.py 2008 __init__
self._reader = parsers.TextReader(src, **kwds)

parsers.pyx 540 pandas._libs.parsers.TextReader.__cinit__


pandas.errors.EmptyDataError:
No columns to parse from file
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-17_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-21_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-23_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-26_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-28_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-29_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2020-12-31_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-01_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-04_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-05_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-06_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-07_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-08_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-09_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.28.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.28.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-13_orcamento_2020.csv
START
[WDM] - There is no [linux64] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-14_orcamento_2020.csv
START
[WDM] - Driver [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-15_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-17_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 90 get_orcamento_executado
firefox.find_element_by_name("ctl00$ContentPlaceHolder1$btnExcel").click()

webdriver.py 496 find_element_by_name
return self.find_element(by=By.NAME, value=name)

webdriver.py 976 find_element
return self.execute(Command.FIND_ELEMENT, {

webdriver.py 321 execute
self.error_handler.check_response(response)

errorhandler.py 242 check_response
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException:
Unable to locate element: [name="ctl00$ContentPlaceHolder1$btnExcel"]
None
None
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-20_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-22_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-23_orcamento_2020.csv
START
[WDM] - Getting latest mozilla release info for v0.29.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
[WDM] - Driver has been saved in cache [/home/m/.wdm/drivers/geckodriver/linux64/v0.29.0]

-------------------------------------------------------------------------------
run.py 53 <module>
main()

run.py 48 main
upload_bigQuerry()

run.py 20 upload_bigQuerry
df = io.get_orcamento_executado()

io.py 96 get_orcamento_executado
os.rename(path+'/gdvDespesasExcel.csv', path+'/{}_orcamento_{}.csv'.format(today, year))

FileNotFoundError:
2
No such file or directory
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/gdvDespesasExcel.csv
/mnt/AEB0CCA7B0CC777D/Jlab/gabinete_sv/orcamento_sp/data/orcamento/2020/executado/2021-01-24_orcamento_2020.csv
